version: "3.8"

services:
  solana-bot:
    build: .
    container_name: solana-market-maker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: solana-bot-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - bot-network
    ports:
      - "6379:6379"

volumes:
  redis_data:

networks:
  bot-network:
    driver: bridge
